version: 3.0.{build}
skip_tags: true
image: Visual Studio 2022
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  sonar_token:
    secure: W7pHKhuTW6Lh8WlXJNTOIaOzeuxLi+H6Nqmnm4pr28jM6jyIpOZ+1r10lIQi0eCA
  JAVA_HOME: C:\Program Files\Java\jdk19
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet publish XmlSchemaClassGenerator.Console -c Release -f net462
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator.Console
  - dotnet pack --include-symbols --include-source -c Release xscgen
  - dotnet pack --include-symbols --include-source -c Release xscgen-proj
  - 7z a -mx=9 XmlSchemaClassGenerator.%APPVEYOR_BUILD_VERSION%.zip ".\XmlSchemaClassGenerator.Console\bin\Release\net462\publish\*"
test_script:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"mganss_XmlSchemaClassGenerator" /v:$env:APPVEYOR_BUILD_VERSION /o:"mganss-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="$env:sonar_token" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)\coverage.xml" /d:sonar.coverage.exclusions="**/Program.cs" /d:sonar.exclusions="**/*.*html"
          dotnet build
      }
  - dotnet test /p:CollectCoverage=true XmlSchemaClassGenerator.Tests\XmlSchemaClassGenerator.Tests.csproj /p:Include="[XmlSchemaClassGenerator]*" -f net8.0
  - ps: cp coverage.*.xml ./coverage.xml
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet sonarscanner end /d:sonar.token="$env:sonar_token"
      }
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'XmlSchemaClassGenerator\**\*.*nupkg'
  - path: 'XmlSchemaClassGenerator.Console\**\*.*nupkg'
  - path: 'xscgen\**\*.*nupkg'
  - path: 'xscgen-proj\**\*.*nupkg'
  - path: XmlSchemaClassGenerator.%APPVEYOR_BUILD_VERSION%.zip
deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    auth_token:
      secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
    artifact: /XmlSchemaClassGenerator\..*\.zip/
    draft: true
    on:
      branch: master
